# Generated by Django 3.1 on 2020-08-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='TweetInage',
            new_name='TweetImage',
        ),
    ]
