# Generated by Django 3.1 on 2020-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200827_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='tweets',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
