# Generated by Django 3.1 on 2020-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='TweetImage',
            field=models.ImageField(blank=True, null=True, upload_to='tweets_images/'),
        ),
    ]
