# Generated by Django 3.1 on 2020-08-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20200827_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetlikes',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
