# Generated by Django 3.1 on 2020-08-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_Name', models.CharField(max_length=100)),
                ('pet_address', models.TextField()),
                ('pet_colour', models.TextField(choices=[('1', 'black'), ('2', 'gray'), ('3', 'white'), ('4', 'brown')], max_length=200)),
                ('pet_bread', models.CharField(choices=[('1', 'lab'), ('2', 'golden'), ('3', 'lasiposo'), ('4', 'dabor'), ('5', 'raj'), ('6', 'policec'), ('7', 'pug'), ('8', 'seslo')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='titel',
            field=models.CharField(default='hello1598441737', max_length=100),
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petID', models.CharField(default='pet_1598441737', max_length=100)),
                ('pet_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.petsdetails')),
            ],
        ),
    ]
