# Generated by Django 3.1 on 2020-08-26 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0005_auto_20200826_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='petUser',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pets',
            name='petID',
            field=models.CharField(default='pet_1598444372.771919', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='titel',
            field=models.CharField(default='hello1598444373', max_length=100),
        ),
    ]
