# Generated by Django 3.1 on 2020-08-26 12:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0006_auto_20200826_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='petID',
            field=models.CharField(default='pet_1598444800.5901074', max_length=100),
        ),
        migrations.AlterField(
            model_name='pets',
            name='petUser',
            field=models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='titel',
            field=models.CharField(default='hello1598444801', max_length=100),
        ),
    ]
