# Generated by Django 3.1 on 2020-08-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20200826_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='petID',
            field=models.CharField(default='pet_1598446987.4248695', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='titel',
            field=models.CharField(default='hello1598446987', max_length=100),
        ),
    ]
