# Generated by Django 3.1 on 2020-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20200826_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsdetails',
            name='petID',
            field=models.CharField(default='pet_15984476873193405', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='titel',
            field=models.CharField(default='hello1598447687', max_length=100),
        ),
    ]
