# Generated by Django 3.1 on 2020-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20200826_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsdetails',
            name='petID',
            field=models.CharField(default='pet_15984636417386985', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='titel',
            field=models.CharField(default='hello1598463642', max_length=100),
        ),
    ]
